path:
  ckpt_path: "alvpredictor/output/ckpt/JSUT"
  log_path: "alvpredictor/output/log/JSUT"
  result_path: "alvpredictor/output/result/JSUT"
optimizer:
  batch_size: 16
  lr: 0.01
epoch:
  total_epoch: 200
  save_epoch: 50